### ISSUE TITLE
Can't mute users from the timeline

### ISSUE THREAD

**Issue by Mannivu** [sk22/megalodon#214] opened 2022-12-29 13:02 UTC
**Describe the bug**
When browsing the timeline, the ability to mute a user doesn't work. There's the option under the tree-dots-menu, but it doesn't do anything. Muting users from their profile works fine.

**To Reproduce**
1. Go to your timeline
2. Click on the three-dots-menu on any toot
3. Tap on "Mute XYZ"

**Screenshots and screen recordings**
https://user-images.githubusercontent.com/42747216/209954696-9075aea0-c977-4fd7-9655-296ff9ac8ef3.mp4

**Version**
Megalodon version: 1.1.5+fork.63-play

**Comment by sk22** [comment] 2022-12-29 17:11
duplicate of #206, fixed in next release

**Closed by sk22** 2022-12-29 17:11 UTC
Labels: bug
