### ISSUE TITLE
Editing existing post to add alt-text to image results in "record not found" error and alt-txt not saved.

### ISSUE THREAD

**Issue by sou7611** [sk22/megalodon#185] opened 2022-12-23 01:26 UTC
**Describe the bug**

Post an image without alt-txt
Edit post
Add alt-text
Click "Save"
Observe "Record not found" error
(note - you may have to dismiss the keyboard to see the error message)

Megalodon v1.1.5+fork.62-play (62)
Pixel 7 Pro on December update

**Comment by HerrHulaHoop** [comment] 2022-12-23 11:12
Duplicate of #104

**Comment by sk22** [comment] 2022-12-23 14:17
which itself is an upstream issue: https://github.com/mastodon/mastodon-android/issues/327
might look into working around this at some point

**Closed by sk22** 2022-12-23 14:17 UTC
Labels: bug
