### ISSUE TITLE
Ability to load oldest missing posts first

### ISSUE THREAD

**Issue by McKristoffer** [sk22/megalodon#311] opened 2023-01-17 12:20 UTC
**Is your feature request related to a problem? Please describe.**
Generally, after I wake up and have my morning coffee I like to catch up on the posts that my fedifriends have posted while I was asleep, Same thing when I'm done with work for the day. In my head, the ideal way to do this is chronologically, i.e. scrolling from the oldest posts to the newest. 

In order for me to do that now, I have to click on the "load missing posts" button, then scroll downwards rapidly, and then click it again until I eventually get to the point where I last finished and all the missing posts have been loaded - then I can begin actually going through them, by scrolling back upwards. 

**Describe the solution you'd like**
I imagine it would not be to everyone's liking, but in my head, ideally when the app is opened, the last viewed post should be shown and there should be an option to "load the missing posts" starting with the oldest ones first, until we eventually catch up to the newest ones. 

**Describe alternatives you've considered**
Perhaps there could be a way to switch between this and the previous way of scrolling in the settings somewhere.

**Comment by egooner** [comment] 2023-01-31 17:46
Yes very frustrating when you click load missing posts and then have to find the last one you read ... perhaps an option to load new posts above rather than below or load above or below based upon location of load messages on screen (top or bottom half of screen affects load direction)

**Comment by ianrenton** [comment] 2023-07-12 10:20
Hi, I thought I would have a try implementing this, but I noticed there is essentially the same issue upstream in the official Mastodon android client:

https://github.com/mastodon/mastodon-android/issues/154

What's the Megalodon developers' preference between implementing a feature like this directly in Megalodon vs implementing it upstream and rebasing Megalodon on a new upstream release?

**Comment by sk22** [comment] 2023-07-12 21:25
> What's the Megalodon developers' preference between implementing a feature like this directly in Megalodon vs implementing it upstream and rebasing Megalodon on a new upstream release?

well, my preference is certainly that it gets implemented upstream first. i'd rather avoid having the feature be implemented in megalodon only to have to merge a different upstream implementation at a later point in time.
a few months ago, timeline markers were actually implemented upstream - i thought this might mean that they would also soon be used (to load the home timeline from the saved point in time), but they only ever get saved.. quite some time has passed since then, so yeah, i don't have much hope left that it gets properly implemented upstream any time soon.

that said, if you want to implement it as an upstream PR, and it doesn't get merged there, i'd love to merge it over to megalodon! @ianrenton

**Comment by tinsukE** [comment] 2023-09-01 18:48
@sk22 well, let's see if it gets merged upstream: https://github.com/mastodon/mastodon-android/pull/680

If it doesn't, it might push me to switch to Megalodon!

**Comment by sk22** [comment] 2023-09-01 18:59
oohh, neat, i'll definitely merge that - thanks!!

**Comment by sk22** [comment] 2023-09-01 19:26
except tbh, without #340 being implemented, this feature wouldn't have as much of an effect, i think: when megalodon shows the top of the cached home timeline (e.g. after re-opening the app), people would usually refresh the timeline (because there's no "show missing posts" item at the top), which always loads the newest posts. not sure how this could best be fixed

**Comment by tinsukE** [comment] 2023-09-01 19:32
That shouldn't be complicated to implement (famous last words). Maybe adding another setting as not to break the current UX for people who like it as is.

I have recently switched from Tusky to Mastodon and when opening the app, if I don't do a swipe to refresh, I think I can read the TL without it skipping.

According to my tests, the app automatically starts fetching new posts, I think it is enough if you wait for them to load.

**Comment by sk22** [comment] 2023-09-01 19:35
hm, true, good point.. maybe i'll look into this again soon

**Comment by sk22** [comment] 2023-09-01 20:00
@tinsukE okay, i just merged it into a branch on the megalodon repo and trying it out to see if there's any unexpected behavior or something. just tried it by switching to an account i haven't been logged into in a while, and wow?? this makes a huge difference - i think i'll even make this behavior the default

**Comment by sk22** [comment] 2023-09-01 20:04
> i think i'll even make this behavior the default

except, maybe not, or maybe i can add something to be able to choose the direction while scrolling (like, it really depends on the direction in which you're scrolling)

**Comment by tinsukE** [comment] 2023-09-02 05:51
@sk22 one thing I was thinking about was to add an arrow button that indicates the load direction to the "load missing posts" cell, when you tap it, it would toggle the setting, and rotate up/down.

But I didn't want to create visual changes so it hopefully gets merged upstream.

**Closed** 2023-09-07 16:32 UTC
Labels: feature, help wanted
