### ISSUE TITLE
Add scheduled toots

### ISSUE THREAD

**Issue by mesteryui** [sk22/megalodon#59] opened 2022-11-20 01:53 UTC
Add the function to select the language and the function to scheluded toots and retoots

**Comment by sk22** [comment] 2022-11-20 16:59
The first one is a duplicate of #9 (you mean on a per-toot basis, right?) - also it's easier to track issues if they're one by one, so I've renamed this to just “Add scheduled toots”.
I'll look into it, but it's not a priority for me, for now. Also, I'm not quite sure what you mean by “scheduled retoots”? You mean, I instead of boosting a toot, you can, like, long-press and say “boost at midnight” or something? Not sure if the API ([scheduled_statuses](https://docs.joinmastodon.org/methods/scheduled_statuses/)) supports that, but… maybe

**Closed** 2022-12-29 15:53 UTC
