### ISSUE TITLE
Random App crash

### ISSUE THREAD

**Issue by kevino-techie** [sk22/megalodon#111] opened 2022-11-26 10:50 UTC
I noticed random crashes in version 1.1.4+fork.50 while using the app. No particular steps to reproduce but crash seemed to occur ocassionaly. The app closes suddenly with no error message.
It could be similar to earlier reported #76
Attached crash log (see multiple errors)

![logcat_11-26-2022_16-17-31.txt](https://github.com/sk22/megalodon/files/10096062/logcat_11-26-2022_16-17-31.txt)

**Comment by sk22** [comment] 2022-11-28 09:32
```
java.lang.IllegalArgumentException: start=61 > end=50
	at me.grishka.appkit.imageloader.ListImageLoader.loadRange(ListImageLoader.java:48)
	at me.grishka.appkit.imageloader.ListImageLoader.loadRange(ListImageLoader.java:43)
	at me.grishka.appkit.imageloader.ListImageLoaderWrapper.realScrollStateChanged(ListImageLoaderWrapper.java:333)
	at me.grishka.appkit.imageloader.ListImageLoaderWrapper.access$600(ListImageLoaderWrapper.java:20)
	at me.grishka.appkit.imageloader.ListImageLoaderWrapper$ScrollStopDetector.run(ListImageLoaderWrapper.java:398)
	at android.os.Handler.handleCallback(Handler.java:978)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8089)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

this looks like a bug in @grishka's image loader; nothing i can do about anyway (i don't recall touching any of the code involved in loading images. you could try reproducing the bug with the upstream app)

---

```
java.lang.IllegalStateException: No device push token available
	at org.joinmastodon.android.api.PushSubscriptionManager.registerAccountForPush(PushSubscriptionManager.java:126)
	at org.joinmastodon.android.api.PushSubscriptionManager$2.onError(PushSubscriptionManager.java:203)
	at me.grishka.appkit.api.APIRequest$2.run(APIRequest.java:41)
	at android.os.Handler.handleCallback(Handler.java:978)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8089)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

this looks like your previous issue #71 and upstream bug mastodon#398, which was fixed in a recent upstream commit and should then also be fixed in the next megalodon release.

generally, please try reproducing new bugs with the official/upstream mastodon app, too (the upstream.apk i provide with each release is compiled from the respective source megalodon is based on). it's probably more helpful to create issues about upstream bugs in the official repo as they should be fixed there anyway.

**Closed by sk22** 2022-11-28 09:32 UTC
