### ISSUE TITLE
UnifiedPush Support

### ISSUE THREAD

**Issue by KaiserCalm** [sk22/megalodon#563] opened 2023-06-10 14:52 UTC
**Is your feature request related to a problem? Please describe.**
Using an OS like DivestOS or GrapheneOS without GP Services prevents push notifications from functioning, which makes probably currently the best Mastodon Android app for me not unusable.

**Describe the solution you'd like**
An implementation of [UnifiedPush](https://unifiedpush.org/developers/android/)  would be a great fix to this issue and allow me, and other people who don't want to depend on Google be able to receive push notifications.

**Describe alternatives you've considered**
[Tusky](https://github.com/tuskyapp/Tusky/pull/2303)  is currently, if I'm not misstaken, the only Android app to support UnifiedPush, which is what I've been using ever since I realised that I don't receive push notifications.

**Additional context**
It's kind of a shame that something like UnifiedPush exists, but most app developers aren't keen on supporting it, which would honestly be the only way UnifiedPush could get popular. I get why, because the userbase for it isn't that big and most people *definitely* aren't completely degoogled, but damn would it be nice if more apps did use it.

**Comment by sk22** [comment] 2023-06-10 16:31
duplicate of #108 (and #120)

**Closed by sk22** 2023-06-10 16:31 UTC
Labels: feature
