### ISSUE TITLE
Check notifications locally

### ISSUE THREAD

**Issue by d4f5409d** [sk22/megalodon#418] opened 2023-02-07 17:50 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I don't get any notifications because I don't have Google Services installed.

**Describe the solution you'd like**
Let the app check locally (fetch informations in the background on a time based period) for available notifications.

**Describe alternatives you've considered**
Add support for self hosted Firebase alternative (unifiedpush for example), or
Encourage sk22 to host a push messaging service for Megalodon and transfer requests from Firebase to that and we would be fine.

**Additional context**

**Comment by sk22** [comment] 2023-02-08 08:06
i'd consider this a duplicate of #120 – also, as far as i can tell (i haven't really touched upstream's push notification implementation), it already connects to a self-hosted fcm endpoint (hard-coded: https://app.joinmastodon.org/relay-to/fcm), but i don't know how that works to be honest.
i might make this URL customizable if that would make sense, but no, i won't host anything myself, sorry 😅

**Closed by sk22** 2023-02-08 08:06 UTC
Labels: feature
