### ISSUE TITLE
Redirection dialog

### ISSUE THREAD

**Issue by muznyo** [sk22/megalodon#420] opened 2023-02-08 00:36 UTC
**Is your feature request related to a problem? Please describe.**
Old users who migrated to new account still have old account. But if you go to old account, it won't redirect.

**Describe the solution you'd like**
Add a dialog or a message, basically some information that it's inactive account and redirect it to new one

**Describe alternatives you've considered**

**Additional context**

**Comment by sk22** [comment] 2023-02-08 08:00
duplicate of #300

**Closed by sk22** 2023-02-08 08:00 UTC
Labels: feature
