### ISSUE TITLE
Crashes when opening profile

### ISSUE THREAD

**Issue by realpixelcode** [sk22/megalodon#472] opened 2023-03-21 01:41 UTC
**Describe the bug**

Megalodon crashes when opening any profile.

**To reproduce**

1. Open any profile.

**Does this happen in the official app?**

No.

**Version**

Megalodon version: v1.2.0+fork.80 (80)

https://user-images.githubusercontent.com/52963327/226501138-d79bdfd9-dd8c-45ba-b83f-f0710109c305.mp4

**Comment by sk22** [comment] 2023-03-21 08:49
duplicate of #469

**Closed by sk22** 2023-03-21 08:49 UTC
Labels: bug
