### ISSUE TITLE
Duplicate posts in timeline

### ISSUE THREAD

**Issue by robin-161** [sk22/megalodon#707] opened 2023-07-12 19:05 UTC
**Describe the bug**
When scrolling down the timeline a bunch (around 15) of the posts that I already viewed are showing up again in the exact same order.

**To reproduce**
1. Open App
2. View and scroll down timeline

**Does this happen in the official app?**
No

**Version**
Megalodon version: 1.2.3+fork.94

**Comment by sk22** [comment] 2023-07-12 21:18
is (or was) there a "load missing posts" item in between? in this case, i'm assuming it's this issue (which does happen on the official app) https://github.com/mastodon/mastodon-android/issues/142 and would be a duplicate of https://github.com/sk22/megalodon/issues/494

**Comment by sk22** [comment] 2023-07-14 16:49
let me know if this is something other than what i've described and linked; until then, i'll close this

**Closed by sk22** 2023-07-14 16:49 UTC
Labels: bug

**Comment by robin-161** [comment] 2023-07-24 20:06
Yeah, seems to be indeed a duplicate of https://github.com/sk22/megalodon/issues/494
